FROM node:14.15.0-alpine
RUN mkdir -p /var/www/src/nuxt
# timezone
ARG TZ
WORKDIR /var/www/src/nuxt
COPY ./src/nuxt/ /var/www/src/nuxt/

RUN apk update && \
  apk upgrade && \
  apk add --no-cache make gcc g++ python && \
  yarn install

EXPOSE 3000

ENTRYPOINT ["yarn", "run", "dev"]